blog/urls.py
from django.urls import path
from . import views

app_name='blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:blog_id>/',views.detail,name='detail'),

]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from perportfolio import views
from blog import urls

urlpatterns = [
    path('',views.home,name='index'),
    path('admin/', admin.site.urls),
    path('blog/',include(urls)),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
import datetime
# Create your models here.

class blog(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField(default=datetime.date.today)
    description = models.TextField(max_length=600)


    def __str__(self):
        return self.title

perportfolio/models.py
from django.db import models

# Create your models here.
class project(models.Model):
    title = models.CharField(max_length=100)
    description=models.CharField(max_length=250)
    image=models.ImageField(upload_to="perportfolio/images")
    url=models.URLField(blank=True)



    def __str__(self):
        return self.title


class skills(models.Model):
    title=models.CharField(max_length=10)
    progress=models.CharField(max_length=3)

    def __str__(self):
        return self.title

class experience(models.Model):
    title=models.CharField(max_length=100)
    duration=models.CharField(max_length=25)
    description=models.CharField(max_length=300)

    

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import blog
# Create your views here.
def home(request):
    blogs= blog.objects.order_by('-date')

    return render( request ,'blog/all_blogs.html',{'blogdict':blogs})

def detail(request, blog_id):
    detailedblog = get_object_or_404(blog,pk=blog_id)
    return render(request , 'blog/blog_details.html', {'dblog':detailedblog})

perportfolio/views.py
from django.shortcuts import render,get_object_or_404
from .models import project, skills , experience
from blog.models import blog
# Create your views here.
def home(request):
    projects = project.objects.all()
    skill = skills.objects.all()
    exp = experience.objects.all()
    blo= blog.objects.all()[:2]
    return render(request, 'perportfolio/index.html', {'proj': projects , 'skill' : skill ,'ep':exp, 'blogs':blo } )

blog/templates/blog/all_blogs.html
{% extends 'perportfolio/base.html' %}

{% block content %}

<div class="bg-dark" style="height: 400px; width:100%;">
<h1 class="text-center" style="font-size:100px;color: white;padding-top:100px;"> Blogs </h1>
</div>
<br>

<div class="text-center">
{% for blog in blogdict %}
<a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
<p>{{ blog.date|date:'M d Y'|upper  }}</p>
<p>{{ blog.description|striptags|truncatechars:100 }}</p>

{% endfor %}
</div>
{% endblock %}

blog/templates/blog/blog_details.html
{% extends 'perportfolio/base.html' %}

{% block content %}
<h1 class="mt-2 text-center">{{ dblog.title }}</h1>

<h2>{{ dblog.date|date:'F jS Y'}}</h2>

{{ dblog.description|safe }}
{% endblock %}

perportfolio/templates/perportfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <title>Vedant Pawar</title>
  </head>
  <body >
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    {% load static %}
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-secondary">
        <a class="navbar-brand" >Vedant Pawar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% static 'perportfolio/res.pdf' %}">Resume</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark"  href="{% url 'blog:home' %}">Blog</a>
            </li>
            </ul>
        <ul class="navbar-nav ml-auto ">
            <li class="nav-item">
                <a class="fa fa-linkedin fa-2x" href="https://www.linkedin.com/in/vedpawar/" style="color:black;padding-right:20px;"></a> 
            </li>
            <li class="nav-item">
                <a class="fa fa-github fa-2x" href="https://github.com/Ved30" style="color:black"></a>
            </li>
     

        </ul>



        </div>


   


      </nav>
    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

perportfolio/templates/perportfolio/index.html
{% extends 'perportfolio/base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" src="style.css">

<div class="text-center">
<img src="{% static 'perportfolio/IMG_20180122_105945_Bokeh__01.jpg' %}" class="rounded  img-thumbnail" height="400" width="400">
<p class="display-4 font-weight-bold">Welcome to my portfolio</p>
</div>  
<br>
<h2 class="mt-5">Projects and Certifications:</h2>
<br>
<hr>
<div class="row">
{% for proj in proj %}
<div class="col-lg-4 col-md-6">
{% if  proj.url  %}
<a href="{{ proj.url }}">
<img src="{{ proj.image.url }}" class="rounded img-thumbnail img-fluid"></img>
{% endif %}
</a>
<h3>{{ proj.title }}</h3>
<p class="text-wrap">{{proj.description}}</p>
</div>
{% endfor %}
</div>
<hr>
{% for blog in blogs %}
<a href="{% url 'blog:detail' blog.id %}"><h2 class="mt-5 text-center"> {{ blog.title }}</h2></a>
<p class="text-center">{{ blog.date|date:'M d Y'|upper  }}</p>
<p class="text-center">{{ blog.description|striptags|truncatechars:100 }}</p>


{% endfor %}
<hr>
<h2 class="mt-5"> Skills: </h2>
{% for ski in skill %}
<h3 class="d-inline" style="padding-left: 20px;padding-right: 20px;">{{ ski.title }}</h3>
{% endfor %}

<hr>
<h2 class="mt-5">Experience:</h2>
{% for exp in ep %}
<h3>{{ exp.title }}</h3>
<h4>{{ exp.duration }}</h4>
<p class="text-wrap">{{ exp.description }}</p>
{% endfor %}
{% endblock %}